apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# full overlay - for larger vps (8+ vcpu, 16gb+ ram)
# e.g., hetzner cx42 (~â‚¬15/mo)
# includes local ollama for embeddings

resources:
  - ../../base
  - ollama.yaml

patches:
  - path: config-patch.yaml
  - path: resource-patch.yaml
