apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# minimal overlay - for small vps (2 vcpu, 4gb ram)
# e.g., hetzner cx21 (~â‚¬4/mo)
# uses external apis only (no local models)

resources:
  - ../../base

patches:
  - path: config-patch.yaml
  - path: resource-patch.yaml
